### ISSUE TITLE
Typescript migration (Mostly done, minor help needed)

### ISSUE THREAD

**Issue by swittk** [glancemoney/react-native-number-pad#3]
Hi there. I stumbled across this wonderful-looking library and found that it didn't use Typescript, but that Typescript was in the roadmap and Contributions were open.

So I inspected the components and such and added typings to them, so much of the work is now done.
However, I do not know the proper way to configure Typescript for publishing to NPM 😅, just that minor change and I think this would be done.

Here's the code in question
https://github.com/swittk/react-native-numpad/tree/typescript

**Comment by cjroth** [comment]
Thank you! I'll take a look later this week when I have some time :) I really appreciate this!
