### ISSUE TITLE
Usage of Pressable API

### ISSUE THREAD

**Issue by apenab** [glancemoney/react-native-number-pad#5]
Because the documentation itself says this:

![image](https://user-images.githubusercontent.com/22795807/112882239-b3276980-909a-11eb-88e6-6ae168453339.png)

Maybe we can use the [`Pressable`](https://reactnative.dev/docs/pressable) API instead of the `TouchableOpacity`. 
With the use of `onLongPress` that `Pressable` brings, it is possible to manage in a better way the way to completely delete the entry data

**Comment by cjroth** [comment]
This makes sense, now that TypeScript is merged, I'd accept a PR that supports this.
